# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

rack_version = ENV['rack'].to_s
rack_version = nil if rack_version.empty? || (rack_version == 'stable')
rack_version = { github: 'rack/rack' } if rack_version == 'head'

tilt_version = ENV['tilt'].to_s
tilt_version = nil if tilt_version.empty? || (tilt_version == 'stable')
tilt_version = { github: 'jeremyevans/tilt' } if tilt_version == 'head'

gem 'erubi'
gem 'haml'
gem 'hamlit', '>= 3'
gem 'rack', rack_version
gem 'rack-protection', path: '../rack-protection'
gem 'rack-test'
gem 'rake', '>= 12.3.3'
gem 'rspec', '~> 3'
gem 'sinatra', path: '..'
gem 'slim'
gem 'tilt', tilt_version
gem 'yajl-ruby', platforms: [:ruby] # c-ext
