# frozen_string_literal: true

source 'https://rubygems.org'
# encoding: utf-8

gem 'rake'

rack_version = ENV['rack'].to_s
rack_version = nil if rack_version.empty? || (rack_version == 'stable')
rack_version = { github: 'rack/rack' } if rack_version == 'head'
gem 'rack', rack_version

gem 'sinatra', path: '..'

gemspec

gem 'rack-test', github: 'rack/rack-test'
